### ISSUE TITLE
texture2D Incompatible types

### ISSUE THREAD

**Issue by xiaozhuai** [walt-grace/glsl-plugin-idea#11]
```glsl
gl_FragColor = texture2D(inputImageTexture, textureCoordinateToUse);
```
> Incompatible types in initialization (and no available implicit conversion).

```glsl
gl_FragColor = vec4(texture2D(inputImageTexture, textureCoordinate).rgb, 1.0);
```
> Too few arguments to constructor of 'vec4'.

**Comment by walt-grace** [comment]
@xiaozhuai 
Thanks for the feedback. I'll have a look at that.

**Comment by xiaozhuai** [comment]
> @xiaozhuai I need the types of _inputImageTexture_ and _textureCoordinateToUse_

```
varying highp vec2 textureCoordinate;
uniform sampler2D inputImageTexture;
```

**Comment by walt-grace** [comment]
I see where the problem lies. Texture2D is actually a constructor and these are not handled yet. I will have a look and see if I can get it with the next release.

**Comment by xiaozhuai** [comment]
> I see where the problem lies. Texture2D is actually a constructor and these are not handled yet. I will have a look and see if I can get it with the next release.

`texture2D` and `textureCube` only works on glsl es 2.0, they are replaced by `texture` on 3.0.
So I guess if we can just add some declarations in `glsl-builtin-functions.glsl`
```glsl
vec4 texture2D(sampler2D _sampler, vec2 P);
ivec4 texture2D(isampler2D _sampler, vec2 P);
uvec4 texture2D(usampler2D _sampler, vec2 P);
vec4 texture2D(sampler2D _sampler, vec2 P, float bias);
ivec4 texture2D(isampler2D _sampler, vec2 P, float bias);
uvec4 texture2D(usampler2D _sampler, vec2 P, float bias);
vec4 textureCube(samplerCube _sampler, vec3 P);
ivec4 textureCube(isamplerCube _sampler, vec3 P);
uvec4 textureCube(usamplerCube _sampler, vec3 P);
vec4 textureCube(samplerCube _sampler, vec3, float bias);
ivec4 textureCube(isamplerCube _sampler, vec3, float bias);
uvec4 textureCube(usamplerCube _sampler, vec3, float bias);
```

**Comment by walt-grace** [comment]
I actually meant texture2D. 

We cannot add them as functions because they are not functions, but constructors, and texture constructors are not implemented yet. 

The error shown is false negative so it's not the end of the world. But in any case, I will either disable these false negative errors or build a new feature handling texture constructors. I haven't touched it so I don't know how complicated it should be.

**Comment by xiaozhuai** [comment]
> I actually meant texture2D.
> 
> We cannot add them as functions because they are not functions, but constructors, and texture constructors are not implemented yet.
> 
> The error shown is false negative so it's not too bad. But in any case, I will either disable these false negative errors or build a new feature handling texture constructors. I haven't touched it so I don't know how complicated it should be.

I don't understand that `texture2D` is a constructor. 
According to [https://thebookofshaders.com/glossary/?search=texture2D](https://thebookofshaders.com/glossary/?search=texture2D), it's a normal function which returns `vec4`.

**Comment by xiaozhuai** [comment]
https://github.com/walt-grace/glsl-plugin-idea/blob/4620654d22bfe01fc81f4710294956af9370b024/src/main/kotlin/glsl/data/GlslDefinitions.kt#L148-L189

So the problem may be treat `texture2D` as a type, but it's not.

**Comment by walt-grace** [comment]
Ahh you are right! It's a function but at the same time it's also definitely a type. In fact, it's an opaque type. In any case, I should have a look to make the annotator differs between the type and the function.

**Comment by xiaozhuai** [comment]
Hello @walt-grace , any progress here? Wish you all the best! And would you please leave a donation way, I'd donate your awesome work if you like.

**Comment by walt-grace** [comment]
Hi @xiaozhuai sorry for the late response. I didn't have time recently. I will try to release this week.

**Comment by walt-grace** [comment]
@xiaozhuai 
PS
Thanks a lot for your appreciation. My work is free for the public :) Fortunately I don't need the money, but I'm sure there are many people or organisations that need money, so feel free to donate where ever you feel like on my behalf :)

**Comment by xiaozhuai** [comment]
> ```glsl
> texture
> ```

I will have a look at this problem again and try to solve it.

**Comment by walt-grace** [comment]
@xiaozhuai 
Finally the fix is done and the new version is released. Please let me know if all ok.

**Comment by xiaozhuai** [comment]
> @xiaozhuai Finally the fix is done and the new version is released. Please let me know if all ok.

Perfect! It works like a charm. Thanks for your great work!
<img width="631" alt="image" src="https://user-images.githubusercontent.com/4773701/226894766-4093fa8c-2dd4-4bc5-a566-333c666654dd.png">

**Comment by walt-grace** [comment]
Cool I'm happy. 
A different question. Did you change the operators color or it changed automatically after the update? 
If yes, this is not expected...

**Comment by xiaozhuai** [comment]
You mean `()` and `{}`? These color was taken over by a plugin named `Rainbow Brackets`.

**Comment by xiaozhuai** [comment]
@walt-grace BTW, this plugin is awesome! I use it at my everyday work. I really appreciates the work you've done here.
I'd like to contribute to it by donation. It's just to buy you some coffee.
So... where can I send you some money? 

Thanks again!

**Comment by walt-grace** [comment]
@xiaozhuai 
Thanks for you replay. Then it all works as expected. 

And regarding your question, I really appreciate that but currently I don't have any platform where I get donations nor I'm sure if I need one. Next time when you go on the street and you see someone that you think needs a few bucks, then give it him and say that is from me :) 

Have a lovely day. If all good, then I'll close the ticket.

**Comment by walt-grace** [comment]
BTW, I found bugs. The texture3D and textureCube will not work properly. I already submitted the changes. Will be probably approved tomorrow.
